# version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: fueleu_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fueleu
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fueleu_backend
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/fueleu
      NODE_ENV: production
    ports:
      - '3001:3001'
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npm run migrate && npm run seed && npm start"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fueleu_frontend
    environment:
      VITE_API_URL: http://fueleu_backend:3001
    ports:
      - '5173:80'
    depends_on:
      - backend

volumes:
  pgdata:
